// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorResponse Error response
type ErrorResponse struct {
	// Code Status code
	Code uint32 `json:"code"`

	// Message Status message
	Message string `json:"message"`
}

// PostMessageRequest Message parameters for posting
type PostMessageRequest struct {
	// Contents Message contents
	Contents string `json:"contents"`
}

// PostMessageResponse Result of message posting
type PostMessageResponse = map[string]interface{}

// ViewMessagesResponse Available messages for viewing
type ViewMessagesResponse struct {
	// Items Messages data items available for viewing
	Items []ViewMessagesResponseItem `json:"items"`
}

// ViewMessagesResponseItem Message data available for viewing
type ViewMessagesResponseItem struct {
	// Contents Message contents
	Contents string `json:"contents"`

	// CreatedAt Message creation time formatted as RFC3339
	CreatedAt time.Time `json:"created_at"`

	// Id Message id
	Id string `json:"id"`
}

// ViewMessagesParams defines parameters for ViewMessages.
type ViewMessagesParams struct {
	// PaginationPageNumber Messages page to view.
	PaginationPageNumber *uint32 `form:"pagination.pageNumber,omitempty" json:"pagination.pageNumber,omitempty"`

	// PaginationPageSize Number of messages per page.
	PaginationPageSize *uint32 `form:"pagination.pageSize,omitempty" json:"pagination.pageSize,omitempty"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFZdj+s0EP0rZuAxbdOWCyJvK8THCris9iKQuFSraTLJ+iqxvbaz21L1v6NxPppuU7a7Qry1seecMzNn",
	"bO8g1ZXRipR3kOzApfdUYfj5nbXa3pIzWjniD5hl0kutsLyx2pD1khwkOZaOIsjIpVYaXoekiRW2Df5L",
	"QQRmEMOsWcA8Dvvg0ddOhMUIaIOVKQmSOIJc2wo9JFBL5ZcLiMBvDUECUnkqyMI+goqcw+I8bLc+QIZf",
	"fzpAOW+lKmC/j8DSQy0tZZB8hFZNF73q9+v1J0o9M99o539p1m/poSbnX1mvNlgYtFiRJ+tErq0w2nmp",
	"itH6Kd/1bByq3zFM90cqSy3+0LbMPrsg8RbhxZTf5JFbcnXphc67xnTpwgjd75KeWjr3Rr6rR5Qlrkvq",
	"+JoaP0p6akiPKyw9VefL60SGHkXYJLBHPgbsIb6wlEMCn88OwzZrJ202ltm1p4qzbsuA1uL2pD0N+urC",
	"YgXIt5kyZHoux//BlhGkltBTdof+X4B5j9RKeFkFkRV6T5lAJ26//3a5XH5zRLmI468m8XwSL36bv0vi",
	"L5P43Z/x10kcw+CwydDThPHGRMnsvBiZHZHhOp0vlnyISPUzqcLfQzJ/afwCxqBcgyKcNp2Dpcr1qaSr",
	"m+vQMjSmlGkoEWcjfVB2dfgqrm6uIYJHsq6JnE/jacyZakMKjYQEluFTBAb9fWjyrJsl/lPQSH/YjP3Z",
	"68JRxo4JlNdZu6Fza4DujkBIPp6dPsNV9joYccqjxqsPNdktRKCw4twMFlIFnilvf19Xa7IQtXccK33d",
	"DbOPnstpIAdHmBOGbBB3oagP8m8alzS/TNOKTdOMeOjBIo4Hgxgm/tDi2SfHuncDvtceTY3VnllMuDpN",
	"ybm8LvtLfwphX4516f8zRcdvkjEpStSKNoZSnn06eoaECXN1VaHdtr7r+8alxYIt1170PJErDuBL6dTV",
	"fP31rh4xtTlcjzAk5bj+IcLwLeuu88eBPYLNJJPOlLh9/3yN276ZeCx+sLo24wB3PBt3LyS42v8TAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
