// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ErrorResponse Error response
type ErrorResponse struct {
	// Code Status code
	Code uint32 `json:"code"`

	// Message Status message
	Message string `json:"message"`
}

// PostMessageRequest Message parameters for posting
type PostMessageRequest struct {
	// Contents Message contents
	Contents string `json:"contents"`
}

// PostMessageResponse Result of message posting
type PostMessageResponse = map[string]interface{}

// ViewMessagesResponse Available messages for viewing
type ViewMessagesResponse struct {
	// Items Messages data items available for viewing
	Items []ViewMessagesResponseItem `json:"items"`
}

// ViewMessagesResponseItem Message data available for viewing
type ViewMessagesResponseItem struct {
	// Contents Message contents
	Contents string `json:"contents"`

	// CreatedAt Message creation time formatted as RFC3339
	CreatedAt time.Time `json:"created_at"`

	// Id Message id
	Id string `json:"id"`
}

// ViewMessagesParams defines parameters for ViewMessages.
type ViewMessagesParams struct {
	// PaginationPageNumber Messages page to view.
	PaginationPageNumber *uint32 `form:"pagination.pageNumber,omitempty" json:"pagination.pageNumber,omitempty"`

	// PaginationPageSize Number of messages per page.
	PaginationPageSize *uint32 `form:"pagination.pageSize,omitempty" json:"pagination.pageSize,omitempty"`
}

// PostMessageJSONRequestBody defines body for PostMessage for application/json ContentType.
type PostMessageJSONRequestBody = PostMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// View messages
	// (GET /messages)
	ViewMessages(w http.ResponseWriter, r *http.Request, params ViewMessagesParams)
	// Post message
	// (POST /messages)
	PostMessage(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// View messages
// (GET /messages)
func (_ Unimplemented) ViewMessages(w http.ResponseWriter, r *http.Request, params ViewMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Post message
// (POST /messages)
func (_ Unimplemented) PostMessage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ViewMessages operation middleware
func (siw *ServerInterfaceWrapper) ViewMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ViewMessagesParams

	// ------------- Optional query parameter "pagination.pageNumber" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pagination.pageNumber", r.URL.Query(), &params.PaginationPageNumber, runtime.BindQueryParameterOptions{Type: "integer", Format: "uint32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pagination.pageNumber"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagination.pageNumber", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pagination.pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pagination.pageSize", r.URL.Query(), &params.PaginationPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "uint32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pagination.pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagination.pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ViewMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMessage operation middleware
func (siw *ServerInterfaceWrapper) PostMessage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/messages", wrapper.ViewMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/messages", wrapper.PostMessage)
	})

	return r
}

type ViewMessagesRequestObject struct {
	Params ViewMessagesParams
}

type ViewMessagesResponseObject interface {
	VisitViewMessagesResponse(w http.ResponseWriter) error
}

type ViewMessages200JSONResponse ViewMessagesResponse

func (response ViewMessages200JSONResponse) VisitViewMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ViewMessagesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ViewMessagesdefaultJSONResponse) VisitViewMessagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PostMessageRequestObject struct {
	Body *PostMessageJSONRequestBody
}

type PostMessageResponseObject interface {
	VisitPostMessageResponse(w http.ResponseWriter) error
}

type PostMessage200JSONResponse PostMessageResponse

func (response PostMessage200JSONResponse) VisitPostMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostMessagedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response PostMessagedefaultJSONResponse) VisitPostMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// View messages
	// (GET /messages)
	ViewMessages(ctx context.Context, request ViewMessagesRequestObject) (ViewMessagesResponseObject, error)
	// Post message
	// (POST /messages)
	PostMessage(ctx context.Context, request PostMessageRequestObject) (PostMessageResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ViewMessages operation middleware
func (sh *strictHandler) ViewMessages(w http.ResponseWriter, r *http.Request, params ViewMessagesParams) {
	var request ViewMessagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ViewMessages(ctx, request.(ViewMessagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ViewMessages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ViewMessagesResponseObject); ok {
		if err := validResponse.VisitViewMessagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMessage operation middleware
func (sh *strictHandler) PostMessage(w http.ResponseWriter, r *http.Request) {
	var request PostMessageRequestObject

	var body PostMessageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMessage(ctx, request.(PostMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMessageResponseObject); ok {
		if err := validResponse.VisitPostMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFZtj+M0EP4rZuBj2qYtByLfFsRLBXdUPQQSR3Vyk0nWq8T22pPdlir/Hdl52WSbst3Vgu5bG3ueeXue",
	"GR8hVoVWEiVZiI5g42ssuP/5vTHKbNBqJS26DzxJBAkleb42SqMhgRailOcWA0jQxkZodw5RbctMY/yX",
	"hAB0z8Z5TTzm0Ow9cSot84cB4J4XOkeIwgBSZQpOEEEpJC0XEAAdNEIEQhJmaKAKoEBreXYetj3vIcOv",
	"Pz9AWTJCZlBVARi8LYXBBKIP0ETTWm+7+2p3gzE5z2tl6W19vsHbEi09s16NMdPc8AIJjWWpMkwrS0Jm",
	"o/WT1PZsHKq70U/3J8xzxf5QJk8+uyDxBuHJlF/EkQ3aMiem0rYxbbow4u53gfeNO/tCf1d3XOR8l2Pr",
	"r67xncD72umwwoKwOF9eyxJOnPlLjHfIQ8AO4guDKUTw+exBbLNGabOxzFaEhcu6KQM3hh9O2lOjby8s",
	"lod8GSl9pudy/B9oGUBskBMmHzn9C7C7I5RkJAofZMGJMGHcss0P3y2Xy28GLhdh+NUknE/CxW/zN1H4",
	"ZRS++TP8OgpD6A2bhBNOHN5YUCI5H4xIBs74Lp4vlm6ICPkLyoyuIZo/JT+P0StXrwinTXfGQqbqNKSr",
	"9cq3rCZ9Iy9BPq637Td2tV5BAHdobG01n4bT0GWpNEquBUSw9J8C0JyufYNnrY7cnwxHeuOI2M1d68eY",
	"Y4vv0yppLrRM9dDt+IPow1nlaVdhUp6EUyczd3pbojlAAJIXLjPt0vJ+pu76u7LYoYGg2W8u0udtlyp4",
	"HE4N2Rtflmk0PrgLg3ov/sbxkOaXxbR1hKnl7XuwCMOeCL3atc5F7F3ObqyL+9jz99yxVNPsEb2YLeMY",
	"rU3LvFv4U/D3Ul7m9GoRDd8jY6FIVkrca4yd7nHwBPHqsmVRcHNoeNf1zZWWZ45y8CCSbRWA20enpHab",
	"ryP1CKd7mxFqRaOlb1VyeLVKjDw3quH0IFNi9R+yY2z7X0qOT50bLrfeW3GMGs6g+X5sxd2fr/tJIqzO",
	"+eHd4zOn2f2EePajUaUeB/j4BDG31T8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
