// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// ErrorResponse Error response
type ErrorResponse struct {
	// Code Status code
	Code uint32 `json:"code"`

	// Message Status message
	Message string `json:"message"`
}

// PostMessageRequest Message parameters for posting
type PostMessageRequest struct {
	// Contents Message contents
	Contents string `json:"contents"`
}

// PostMessageResponse Result of message posting
type PostMessageResponse = map[string]interface{}

// ViewMessagesResponse Available messages for viewing
type ViewMessagesResponse struct {
	// Items Messages data items available for viewing
	Items []ViewMessagesResponseItem `json:"items"`
}

// ViewMessagesResponseItem Message data available for viewing
type ViewMessagesResponseItem struct {
	// Contents Message contents
	Contents string `json:"contents"`

	// CreatedAt Message creation time formatted as RFC3339
	CreatedAt time.Time `json:"created_at"`

	// Id Message id
	Id string `json:"id"`
}

// ViewMessagesParams defines parameters for ViewMessages.
type ViewMessagesParams struct {
	// PaginationPageNumber Messages page to view.
	PaginationPageNumber *uint32 `form:"pagination.pageNumber,omitempty" json:"pagination.pageNumber,omitempty"`

	// PaginationPageSize Number of messages per page.
	PaginationPageSize *uint32 `form:"pagination.pageSize,omitempty" json:"pagination.pageSize,omitempty"`
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFZdb+M2EPwr7LaPsi3bvRbVW1D0I2jvGuSKFujVCGhppfAgkQy5ytk1/N+LpT4sx3LjBMW92SJ3dnZ3",
	"huQOUlNZo1GTh2QHPr3HSoafPzhn3C16a7RH/iCzTJEyWpY3zlh0pNBDksvSYwQZ+tQpy+uQNLHCtcF/",
	"a4jADmI4axYwj8Pek6Tai7AYAW5kZUuEJI4gN66SBAnUStNyARHQ1iIkoDRhgQ72EVTovSzOw3brA2T4",
	"7ZcDlCendAH7fQQOH2rlMIPkA7RsuuhVv9+sP2JKnPnGeHrbrN/iQ42eXtivNlhY6WSFhM6L3DhhjSel",
	"i9H+aepmNg7V7xiW+zOWpRF/GldmX1xQeIvwbMmv0sgt+rokYfJuMF25MJLuD4Wf2nT+lfmuHqUq5brE",
	"Ll/T40eFn5qkxx1WhNX59nqRSZIibBKyRz4G7CG+cphDAl/ODmabtU6bjVV2TVhx1W0bpHNyezKeBn11",
	"YbMC5OtEGSo9V+NnkGUEqUNJmN1J+g9g3qOMFqSqQLKSRJgJ6cXtj98vl8vvjlIu4vibSTyfxIvf52+S",
	"+OskfvNX/G0SxzA4bDJJOGG8MVIqO09GZUfJ5DqdL5Z8iCj9K+qC7iGZP2e/gDFo16AJp0PnYKVzc0rp",
	"6uY6jKwRfWsvRYHX2+6buLq5hgge0fkmaj6NpzFXaSxqaRUksAyfIrCS7sOAZ52P+E+BI7NhIfbnrg/H",
	"GKslzOk6azd0Sg3Q3fEHyYezzrPcYTJBhFO2Ga8+1Oi2EIGWFVdmuayQZ8rb39XVGh1E7f3GTF92u+yj",
	"p3QayMHx5YVFF8hdSOq9+gfHKc0v47RiwTT2DjNYxPHAhMHt1pYqDSlnHz3z3g3yvfRYamT2RF7C12mK",
	"3ud12V/4Uwj7clmX9L8xOn6PjFHRota4sZiy7/HoCRLc5euqkm7b6q6fG7dWFiw5OJhkxQF8IZ2qmq++",
	"XtUjoraHqxGGSTmuf4QwfJt11+ljaNHNJFPelnL77ukaj30zIVn85ExtxwHu2Bt3zxS42v8bAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
