version: '3'

includes:
  openapi:
    taskfile: ./tools/openapi/Taskfile.yml
    internal: true

tasks:
  default:
    desc: Run default tasks.
    cmds:
      - task: generate
      - task: lint

  lint:
    desc: Run linter.
    cmds:
      - golangci-lint run

  generate:
    desc: Run all generation task.
    cmds:
      - task: generate-openapi-messaging-bundle
      - task: generate-go
      - task: generate-mocks

  generate-go:
    desc: Run go:generate.
    cmds:
      - go generate ./...

  generate-mocks:
    desc: Generate mocks.
    cmds:
      - go tool mockery

  generate-openapi-messaging-bundle:
    desc: Generate messaging domain OpenAPI bundle.
    cmds:
      - task: openapi:bundle-messaging

  cli-post:
    desc: Post message using CLI.
    vars:
      DATA: '{{default "Hello World!" .DATA}}'
    cmds:
      - go run ./cmd/cli -cmd post -data {{.DATA}}

  cli-view:
    desc: Veiw messages using CLI.
    cmds:
      - go run ./cmd/cli -cmd view
