version: '3'

tasks:
  default:
    desc: Run default tasks.
    cmds:
      - task: generate
      - task: lint

  lint:
    desc: Run linter.
    cmds:
      - golangci-lint run

  generate:
    desc: Run all generation task.
    cmds:
      - task: generate-mocks

  generate-mocks:
    desc: Generate mocks.
    cmds:
      - mockery

  cli-post:
    desc: Post message using CLI.
    vars:
      DATA: '{{default "Hello World!" .DATA}}'
    cmds:
      - go run ./cmd/cli -cmd post -data {{.DATA}}

  cli-view:
    desc: Veiw messages using CLI.
    cmds:
      - go run ./cmd/cli -cmd view
