// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockFileLineStorage creates a new instance of mockFileLineStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFileLineStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFileLineStorage {
	mock := &mockFileLineStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockFileLineStorage is an autogenerated mock type for the FileLineStorage type
type mockFileLineStorage struct {
	mock.Mock
}

type mockFileLineStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFileLineStorage) EXPECT() *mockFileLineStorage_Expecter {
	return &mockFileLineStorage_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type mockFileLineStorage
func (_mock *mockFileLineStorage) Insert(line string) error {
	ret := _mock.Called(line)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(line)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockFileLineStorage_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type mockFileLineStorage_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - line string
func (_e *mockFileLineStorage_Expecter) Insert(line any) *mockFileLineStorage_Insert_Call {
	return &mockFileLineStorage_Insert_Call{Call: _e.mock.On("Insert", line)}
}

func (_c *mockFileLineStorage_Insert_Call) Run(run func(line string)) *mockFileLineStorage_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockFileLineStorage_Insert_Call) Return(err error) *mockFileLineStorage_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockFileLineStorage_Insert_Call) RunAndReturn(run func(line string) error) *mockFileLineStorage_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type mockFileLineStorage
func (_mock *mockFileLineStorage) Read() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockFileLineStorage_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockFileLineStorage_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *mockFileLineStorage_Expecter) Read() *mockFileLineStorage_Read_Call {
	return &mockFileLineStorage_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *mockFileLineStorage_Read_Call) Run(run func()) *mockFileLineStorage_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockFileLineStorage_Read_Call) Return(strings []string, err error) *mockFileLineStorage_Read_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mockFileLineStorage_Read_Call) RunAndReturn(run func() ([]string, error)) *mockFileLineStorage_Read_Call {
	_c.Call.Return(run)
	return _c
}
